# Generated by Django 3.0.6 on 2020-05-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='logo',
            field=models.ImageField(upload_to='image/products_pics'),
        ),
    ]
